### ISSUE TITLE
iofogctl does not allow you to mount volumes in to the agent container

### ISSUE THREAD

**Issue by agibsonccc** [eclipse-iofog/iofogctl#116]
Running on windows and iofog 2, I ran in to an issue where iofog's agent only looks for mounted volumes in the agent path. 

Due to this limitation, you can't really use volumes on windows.
What we need to be able to do as a workaround is specify volumes in the agent, then in the iofog agent configuration we need to specify an absolute path in the configuration file
that is a valid path present in the container.

Right now, docker cping the content/directory you want to use in to the agent container is the only work around.

This was discussed in the iofog slack.

**Comment by SergeRadinovich** [comment]
Thanks @agibsonccc we are working on a solution. 

Right now you can `iofogctl deploy -f volume.yaml` for non-local ECNs and soon you will be able to do the same for your local ECN.

**Comment by Pixcell** [comment]
Closed with: https://github.com/eclipse-iofog/iofogctl/pull/118

The solution is to copy files over to your Agent container, exactly like you would copy local files to your Agent on a remote host.
iofogctl is able to deploy the `Volume` kind (https://iofog.org/docs/2/agent-management/volumes.html)

The YAML used to deploy a microservice that requires some certificates (mounted under /etc/certs) that would be present in your local /tmp folder will look something like this:

```
---
apiVersion: iofog.org/v2
kind: Volume
metadata:
  name: volume-for-msvc-a
spec:
  source: /tmp/
  destination: /tmp/secrets/
  permissions: 666
  agents:
    - agent-1
---
apiVersion: iofog.org/v2
kind: Application
metadata:
  name: my-app
spec:
  microservices:
  - name: msvc-a
    agent:
      name: agent-1
    images:
      ...
    container:
      volumes:
      - hostDestination: /tmp/secrets/
       containerDestination: /etc/certs/
       accessMode: rw
    ...
```
